### ISSUE TITLE
Support KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE to specify the set of files to run

### ISSUE THREAD

**Issue by renehernandez** [KnapsackPro/knapsack-pro-jest#58]
Similar to the https://github.com/KnapsackPro/knapsack_pro-ruby library, add support for `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE` environment to restrict knapsackpro to a subset of file to load balance instead of whole folders.

This would allow us to use knapsackpro as part of our regresion test suite in feature branches, where we detect which tests to run based on which files where changed (as opposed to just running the whole test suite)

**Comment by renehernandez** [comment]
I'll try to come up with an implementation, but some pointers may be helpful :)

**Comment by ArturT** [comment]
I was about to start working on that because another user requested this feature as well.

I prepared a draft idea of how to approach the problem.

We could add `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE`
to [`@knapsack-pro/core`](https://github.com/KnapsackPro/knapsack-pro-core-js/). 

When `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE` has a value, then use test files from the file instead of test files passed from the `@knapsack-pro/jest` or `@knapsack-pro/cypress`. https://github.com/KnapsackPro/knapsack-pro-core-js/blob/f93bcc0a19a25e8752369aea3be03ded8c09ba7a/src/knapsack-pro-core.ts#L27 

We could keep the business logic for `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE` in `@knapsack-pro/core`. Thanks to that, it would work in all Knapsack Pro clients for Jest and Cypress.

Here is the code where `@knapsack-pro/jest` passes a list of test files to `KnapsackProCore`. No need to change anything here. https://github.com/KnapsackPro/knapsack-pro-jest/blob/bdc12106587c1790113548929edb967ea4dce535/src/knapsack-pro-jest.ts#L35 We will just override this on `@knapsack-pro/core` level. Similarly, like we do in Ruby where `KNAPSACK_PRO_TEST_FILE_PATTERN` and `KNAPSACK_PRO_TEST_FILE_EXCLUDE_PATTERN` are ignored when `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE` has a value. https://docs.knapsackpro.com/ruby/reference/#knapsack_pro_test_file_list_source_file

I'll start working on this feature and give an update here.

**Comment by ArturT** [comment]
We've released the `@knapsack-pro/jest` 5.4.0 version. Here is an example how to use `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE` to define a list of test files.
https://github.com/KnapsackPro/knapsack-pro-core-js/pull/62
